FROM islasgeci/geci_diversity:latest
RUN apt update && apt upgrade --yes
RUN apt install curl 
RUN curl -fsSL https://opencode.ai/v2/install | bash
RUN git clone https://github.com/mvillasante/opencode_agents.git /tmp/opencode_agents && \
	mkdir --parents /root/.config/opencode && \
	cp -r /tmp/opencode_agents/* /root/.config/opencode/ && \
	rm -rf /tmp/opencode_agents
